/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ChangePasswordDto,
  ChangeUsernameDto,
  CounterpartiesControllerListV1Params,
  CreateCounterpartyDto,
  CreateInstitutionAccountDto,
  CreateInstitutionDto,
  CreateInventoryLotDto,
  CreateOrderDto,
  CreateOrderSettlementDto,
  CreateRateSnapshotDto,
  CreateSaleExecutionDto,
  CreateTransactionDto,
  CreateUserRequestDto,
  DebtBalancesControllerListV1Params,
  HeldBalancesControllerListV1Params,
  InstitutionAccountsControllerListV1Params,
  InstitutionsControllerListV1Params,
  InventoryLotsControllerListV1Params,
  LoginDto,
  OrderSettlementsControllerListV1Params,
  OrdersControllerListV1Params,
  RateSnapshotsControllerListV1Params,
  RegisterDto,
  SaleExecutionsControllerListV1Params,
  TransactionsControllerListV1Params,
  UpdateCounterpartyDto,
  UpdateInstitutionAccountDto,
  UpdateInstitutionDto,
  UpdateOrderDto,
  UpdateUserDto,
  UsersControllerListV1Params
} from './model';

export const getXeBookAPIBackend = (axiosInstance: AxiosInstance = axios) => {
/**
 * Create a new internal user account and return the authenticated session payload.
 * @summary Register
 */
const authControllerRegisterV1 = (
    registerDto: RegisterDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/v1/auth/register`,
      registerDto,options
    );
  }

/**
 * Authenticate with username and password and return the authenticated session payload.
 * @summary Login
 */
const authControllerLoginV1 = (
    loginDto: LoginDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/v1/auth/login`,
      loginDto,options
    );
  }

/**
 * Return the currently authenticated JWT user payload.
 * @summary Get current auth user
 */
const authControllerMe0V1 = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/v1/auth/me`,options
    );
  }

/**
 * Return the currently authenticated JWT user payload.
 * @summary Get current auth user
 */
const authControllerMe1V1 = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/v1/auth/whoami`,options
    );
  }

/**
 * Create a new internal user.
 * @summary Create user
 */
const usersControllerCreateV1 = (
    createUserRequestDto: CreateUserRequestDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/v1/users`,
      createUserRequestDto,options
    );
  }

/**
 * List internal users with pagination and filters.
 * @summary List users
 */
const usersControllerListV1 = (
    params: UsersControllerListV1Params, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/v1/users`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Fetch one internal user by id.
 * @summary Get user by ID
 */
const usersControllerFindOneV1 = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/v1/users/${id}`,options
    );
  }

/**
 * Update mutable profile fields for one internal user.
 * @summary Update user by ID
 */
const usersControllerUpdateV1 = (
    id: string,
    updateUserDto: UpdateUserDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.patch(
      `/api/v1/users/${id}`,
      updateUserDto,options
    );
  }

/**
 * Hard delete a user when foreign-key constraints allow it.
 * @summary Delete user by ID
 */
const usersControllerRemoveV1 = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/api/v1/users/${id}`,options
    );
  }

/**
 * Change the password of a specific internal user.
 * @summary Change user password by ID
 */
const usersControllerChangePasswordV1 = (
    id: string,
    changePasswordDto: ChangePasswordDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/v1/users/${id}/change-password`,
      changePasswordDto,options
    );
  }

/**
 * Change the username of a specific internal user.
 * @summary Change user username by ID
 */
const usersControllerChangeUsernameV1 = (
    id: string,
    changeUsernameDto: ChangeUsernameDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/v1/users/${id}/change-username`,
      changeUsernameDto,options
    );
  }

/**
 * Freeze a user account by setting it inactive.
 * @summary Freeze user by ID
 */
const usersControllerFreezeV1 = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/v1/users/${id}/freeze`,undefined,options
    );
  }

/**
 * Unfreeze a user account by setting it active.
 * @summary Unfreeze user by ID
 */
const usersControllerUnfreezeV1 = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/v1/users/${id}/unfreeze`,undefined,options
    );
  }

/**
 * Fetch the currently authenticated internal user.
 * @summary Get me
 */
const meControllerFindMeV1 = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/v1/me`,options
    );
  }

/**
 * Update mutable profile fields for the currently authenticated user.
 * @summary Update me
 */
const meControllerUpdateMeV1 = (
    updateUserDto: UpdateUserDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.patch(
      `/api/v1/me`,
      updateUserDto,options
    );
  }

/**
 * Change the password of the currently authenticated user.
 * @summary Change my password
 */
const meControllerChangeMyPasswordV1 = (
    changePasswordDto: ChangePasswordDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/v1/me/change-password`,
      changePasswordDto,options
    );
  }

/**
 * Change the username of the currently authenticated user.
 * @summary Change my username
 */
const meControllerChangeMyUsernameV1 = (
    changeUsernameDto: ChangeUsernameDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/v1/me/change-username`,
      changeUsernameDto,options
    );
  }

/**
 * Create a trade agreement between two internal users.
 * @summary Create order
 */
const ordersControllerCreateV1 = (
    createOrderDto: CreateOrderDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/v1/orders`,
      createOrderDto,options
    );
  }

/**
 * List orders with pagination and filters.
 * @summary List orders
 */
const ordersControllerListV1 = (
    params: OrdersControllerListV1Params, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/v1/orders`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Fetch one order by id.
 * @summary Get order by ID
 */
const ordersControllerFindOneV1 = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/v1/orders/${id}`,options
    );
  }

/**
 * Update mutable order fields such as status or note.
 * @summary Update order by ID
 */
const ordersControllerUpdateV1 = (
    id: string,
    updateOrderDto: UpdateOrderDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.patch(
      `/api/v1/orders/${id}`,
      updateOrderDto,options
    );
  }

/**
 * Create a settlement leg for an order and apply settlement-related balance logic.
 * @summary Create order settlement
 */
const orderSettlementsControllerCreateV1 = (
    createOrderSettlementDto: CreateOrderSettlementDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/v1/order-settlements`,
      createOrderSettlementDto,options
    );
  }

/**
 * List order settlement rows with pagination and filters.
 * @summary List order settlements
 */
const orderSettlementsControllerListV1 = (
    params: OrderSettlementsControllerListV1Params, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/v1/order-settlements`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Fetch one order settlement row by id.
 * @summary Get order settlement by ID
 */
const orderSettlementsControllerFindOneV1 = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/v1/order-settlements/${id}`,options
    );
  }

/**
 * Store a reference FX or market rate that can later be used for approximate breakeven and profit calculations.
 * @summary Create rate snapshot
 */
const rateSnapshotsControllerCreateV1 = (
    createRateSnapshotDto: CreateRateSnapshotDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/v1/rate-snapshots`,
      createRateSnapshotDto,options
    );
  }

/**
 * List stored rate snapshots with pagination and filters.
 * @summary List rate snapshots
 */
const rateSnapshotsControllerListV1 = (
    params: RateSnapshotsControllerListV1Params, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/v1/rate-snapshots`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Fetch one rate snapshot by id.
 * @summary Get rate snapshot by ID
 */
const rateSnapshotsControllerFindOneV1 = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/v1/rate-snapshots/${id}`,options
    );
  }

/**
 * Record acquired inventory, such as buying USDT from an internal user, with the total cost kept for later FIFO profit calculation.
 * @summary Create inventory lot
 */
const inventoryLotsControllerCreateV1 = (
    createInventoryLotDto: CreateInventoryLotDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/v1/inventory-lots`,
      createInventoryLotDto,options
    );
  }

/**
 * List inventory lots and remaining quantities with pagination and filters.
 * @summary List inventory lots
 */
const inventoryLotsControllerListV1 = (
    params: InventoryLotsControllerListV1Params, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/v1/inventory-lots`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Fetch one inventory lot and its sale allocations.
 * @summary Get inventory lot by ID
 */
const inventoryLotsControllerFindOneV1 = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/v1/inventory-lots/${id}`,options
    );
  }

/**
 * Record a realized sale, consume inventory using FIFO, and compute realized profit when the inventory cost currency matches the sale proceeds currency.
 * @summary Create sale execution
 */
const saleExecutionsControllerCreateV1 = (
    createSaleExecutionDto: CreateSaleExecutionDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/v1/sale-executions`,
      createSaleExecutionDto,options
    );
  }

/**
 * List realized sales, proceeds, fees, and calculated profit with pagination and filters.
 * @summary List sale executions
 */
const saleExecutionsControllerListV1 = (
    params: SaleExecutionsControllerListV1Params, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/v1/sale-executions`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Fetch one sale execution and its inventory allocations.
 * @summary Get sale execution by ID
 */
const saleExecutionsControllerFindOneV1 = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/v1/sale-executions/${id}`,options
    );
  }

/**
 * Create a new institution such as a bank, wallet provider, exchange, or cash office.
 * @summary Create institution
 */
const institutionsControllerCreateV1 = (
    createInstitutionDto: CreateInstitutionDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/v1/institutions`,
      createInstitutionDto,options
    );
  }

/**
 * List institutions with pagination and filters.
 * @summary List institutions
 */
const institutionsControllerListV1 = (
    params: InstitutionsControllerListV1Params, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/v1/institutions`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Fetch one institution by id.
 * @summary Get institution by ID
 */
const institutionsControllerFindOneV1 = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/v1/institutions/${id}`,options
    );
  }

/**
 * Update one institution.
 * @summary Update institution by ID
 */
const institutionsControllerUpdateV1 = (
    id: string,
    updateInstitutionDto: UpdateInstitutionDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.patch(
      `/api/v1/institutions/${id}`,
      updateInstitutionDto,options
    );
  }

/**
 * Hard delete one institution when foreign-key constraints allow it.
 * @summary Delete institution by ID
 */
const institutionsControllerRemoveV1 = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/api/v1/institutions/${id}`,options
    );
  }

/**
 * List current held-balance snapshots between owner users and holder users.
 * @summary List held balances
 */
const heldBalancesControllerListV1 = (
    params: HeldBalancesControllerListV1Params, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/v1/held-balances`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * List current debt-balance snapshots between debtors and creditors.
 * @summary List debt balances
 */
const debtBalancesControllerListV1 = (
    params: DebtBalancesControllerListV1Params, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/v1/debt-balances`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Creates one transaction ledger row and applies the related held-balance or debt-balance rules according to the transaction type.
 * @summary Create transaction
 */
const transactionsControllerCreateV1 = (
    createTransactionDto: CreateTransactionDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/v1/transactions`,
      createTransactionDto,options
    );
  }

/**
 * Lists transactions with filters for users, accounts, counterparties, currency, type, method, and occurred-at date range.
 * @summary List transactions
 */
const transactionsControllerListV1 = (
    params: TransactionsControllerListV1Params, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/v1/transactions`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Fetches one transaction by id with related users, accounts, and counterparties.
 * @summary Get transaction by ID
 */
const transactionsControllerFindOneV1 = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/v1/transactions/${id}`,options
    );
  }

/**
 * Create a new external counterparty record.
 * @summary Create counterparty
 */
const counterpartiesControllerCreateV1 = (
    createCounterpartyDto: CreateCounterpartyDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/v1/counterparties`,
      createCounterpartyDto,options
    );
  }

/**
 * List counterparties with pagination and filters.
 * @summary List counterparties
 */
const counterpartiesControllerListV1 = (
    params: CounterpartiesControllerListV1Params, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/v1/counterparties`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Fetch one counterparty by id.
 * @summary Get counterparty by ID
 */
const counterpartiesControllerFindOneV1 = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/v1/counterparties/${id}`,options
    );
  }

/**
 * Update one counterparty.
 * @summary Update counterparty by ID
 */
const counterpartiesControllerUpdateV1 = (
    id: string,
    updateCounterpartyDto: UpdateCounterpartyDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.patch(
      `/api/v1/counterparties/${id}`,
      updateCounterpartyDto,options
    );
  }

/**
 * Hard delete one counterparty.
 * @summary Delete counterparty by ID
 */
const counterpartiesControllerRemoveV1 = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/api/v1/counterparties/${id}`,options
    );
  }

/**
 * Create a specific institution account for an internal user.
 * @summary Create institution account
 */
const institutionAccountsControllerCreateV1 = (
    createInstitutionAccountDto: CreateInstitutionAccountDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/v1/institution-accounts`,
      createInstitutionAccountDto,options
    );
  }

/**
 * List institution accounts with pagination and filters.
 * @summary List institution accounts
 */
const institutionAccountsControllerListV1 = (
    params: InstitutionAccountsControllerListV1Params, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/v1/institution-accounts`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Fetch one institution account by id.
 * @summary Get institution account by ID
 */
const institutionAccountsControllerFindOneV1 = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/v1/institution-accounts/${id}`,options
    );
  }

/**
 * Update one institution account.
 * @summary Update institution account by ID
 */
const institutionAccountsControllerUpdateV1 = (
    id: string,
    updateInstitutionAccountDto: UpdateInstitutionAccountDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.patch(
      `/api/v1/institution-accounts/${id}`,
      updateInstitutionAccountDto,options
    );
  }

/**
 * Hard delete one institution account.
 * @summary Delete institution account by ID
 */
const institutionAccountsControllerRemoveV1 = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/api/v1/institution-accounts/${id}`,options
    );
  }

return {authControllerRegisterV1,authControllerLoginV1,authControllerMe0V1,authControllerMe1V1,usersControllerCreateV1,usersControllerListV1,usersControllerFindOneV1,usersControllerUpdateV1,usersControllerRemoveV1,usersControllerChangePasswordV1,usersControllerChangeUsernameV1,usersControllerFreezeV1,usersControllerUnfreezeV1,meControllerFindMeV1,meControllerUpdateMeV1,meControllerChangeMyPasswordV1,meControllerChangeMyUsernameV1,ordersControllerCreateV1,ordersControllerListV1,ordersControllerFindOneV1,ordersControllerUpdateV1,orderSettlementsControllerCreateV1,orderSettlementsControllerListV1,orderSettlementsControllerFindOneV1,rateSnapshotsControllerCreateV1,rateSnapshotsControllerListV1,rateSnapshotsControllerFindOneV1,inventoryLotsControllerCreateV1,inventoryLotsControllerListV1,inventoryLotsControllerFindOneV1,saleExecutionsControllerCreateV1,saleExecutionsControllerListV1,saleExecutionsControllerFindOneV1,institutionsControllerCreateV1,institutionsControllerListV1,institutionsControllerFindOneV1,institutionsControllerUpdateV1,institutionsControllerRemoveV1,heldBalancesControllerListV1,debtBalancesControllerListV1,transactionsControllerCreateV1,transactionsControllerListV1,transactionsControllerFindOneV1,counterpartiesControllerCreateV1,counterpartiesControllerListV1,counterpartiesControllerFindOneV1,counterpartiesControllerUpdateV1,counterpartiesControllerRemoveV1,institutionAccountsControllerCreateV1,institutionAccountsControllerListV1,institutionAccountsControllerFindOneV1,institutionAccountsControllerUpdateV1,institutionAccountsControllerRemoveV1}};
export type AuthControllerRegisterV1Result = AxiosResponse<void>
export type AuthControllerLoginV1Result = AxiosResponse<void>
export type AuthControllerMe0V1Result = AxiosResponse<void>
export type AuthControllerMe1V1Result = AxiosResponse<void>
export type UsersControllerCreateV1Result = AxiosResponse<void>
export type UsersControllerListV1Result = AxiosResponse<void>
export type UsersControllerFindOneV1Result = AxiosResponse<void>
export type UsersControllerUpdateV1Result = AxiosResponse<void>
export type UsersControllerRemoveV1Result = AxiosResponse<void>
export type UsersControllerChangePasswordV1Result = AxiosResponse<void>
export type UsersControllerChangeUsernameV1Result = AxiosResponse<void>
export type UsersControllerFreezeV1Result = AxiosResponse<void>
export type UsersControllerUnfreezeV1Result = AxiosResponse<void>
export type MeControllerFindMeV1Result = AxiosResponse<void>
export type MeControllerUpdateMeV1Result = AxiosResponse<void>
export type MeControllerChangeMyPasswordV1Result = AxiosResponse<void>
export type MeControllerChangeMyUsernameV1Result = AxiosResponse<void>
export type OrdersControllerCreateV1Result = AxiosResponse<void>
export type OrdersControllerListV1Result = AxiosResponse<void>
export type OrdersControllerFindOneV1Result = AxiosResponse<void>
export type OrdersControllerUpdateV1Result = AxiosResponse<void>
export type OrderSettlementsControllerCreateV1Result = AxiosResponse<void>
export type OrderSettlementsControllerListV1Result = AxiosResponse<void>
export type OrderSettlementsControllerFindOneV1Result = AxiosResponse<void>
export type RateSnapshotsControllerCreateV1Result = AxiosResponse<void>
export type RateSnapshotsControllerListV1Result = AxiosResponse<void>
export type RateSnapshotsControllerFindOneV1Result = AxiosResponse<void>
export type InventoryLotsControllerCreateV1Result = AxiosResponse<void>
export type InventoryLotsControllerListV1Result = AxiosResponse<void>
export type InventoryLotsControllerFindOneV1Result = AxiosResponse<void>
export type SaleExecutionsControllerCreateV1Result = AxiosResponse<void>
export type SaleExecutionsControllerListV1Result = AxiosResponse<void>
export type SaleExecutionsControllerFindOneV1Result = AxiosResponse<void>
export type InstitutionsControllerCreateV1Result = AxiosResponse<void>
export type InstitutionsControllerListV1Result = AxiosResponse<void>
export type InstitutionsControllerFindOneV1Result = AxiosResponse<void>
export type InstitutionsControllerUpdateV1Result = AxiosResponse<void>
export type InstitutionsControllerRemoveV1Result = AxiosResponse<void>
export type HeldBalancesControllerListV1Result = AxiosResponse<void>
export type DebtBalancesControllerListV1Result = AxiosResponse<void>
export type TransactionsControllerCreateV1Result = AxiosResponse<void>
export type TransactionsControllerListV1Result = AxiosResponse<void>
export type TransactionsControllerFindOneV1Result = AxiosResponse<void>
export type CounterpartiesControllerCreateV1Result = AxiosResponse<void>
export type CounterpartiesControllerListV1Result = AxiosResponse<void>
export type CounterpartiesControllerFindOneV1Result = AxiosResponse<void>
export type CounterpartiesControllerUpdateV1Result = AxiosResponse<void>
export type CounterpartiesControllerRemoveV1Result = AxiosResponse<void>
export type InstitutionAccountsControllerCreateV1Result = AxiosResponse<void>
export type InstitutionAccountsControllerListV1Result = AxiosResponse<void>
export type InstitutionAccountsControllerFindOneV1Result = AxiosResponse<void>
export type InstitutionAccountsControllerUpdateV1Result = AxiosResponse<void>
export type InstitutionAccountsControllerRemoveV1Result = AxiosResponse<void>
