/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

export type CounterpartiesControllerListV1Type = typeof CounterpartiesControllerListV1Type[keyof typeof CounterpartiesControllerListV1Type];


export const CounterpartiesControllerListV1Type = {
  PERSON: 'PERSON',
  BUSINESS: 'BUSINESS',
  MERCHANT: 'MERCHANT',
  TRADER: 'TRADER',
  COMPANY: 'COMPANY',
  UNKNOWN: 'UNKNOWN',
} as const;
