/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */
import type { CounterpartiesControllerListV1SortOrder } from './counterpartiesControllerListV1SortOrder';
import type { CounterpartiesControllerListV1Type } from './counterpartiesControllerListV1Type';

export type CounterpartiesControllerListV1Params = {
/**
 * @minimum 1
 * @maximum 9007199254740991
 */
page?: number;
/**
 * @minimum 1
 * @maximum 250
 */
perPage?: number;
/**
 * @minLength 1
 */
select: string;
/**
 * @minLength 1
 */
sortBy: string;
sortOrder?: CounterpartiesControllerListV1SortOrder;
search: string;
type: CounterpartiesControllerListV1Type;
};
