/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

export type CounterpartiesControllerListV1SortOrder = typeof CounterpartiesControllerListV1SortOrder[keyof typeof CounterpartiesControllerListV1SortOrder];


export const CounterpartiesControllerListV1SortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
