/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */
import type { CreateRateSnapshotDtoSource } from './createRateSnapshotDtoSource';

export interface CreateRateSnapshotDto {
  /** @minLength 1 */
  baseCurrency: string;
  /** @minLength 1 */
  quoteCurrency: string;
  /** @minLength 1 */
  rate: string;
  source: CreateRateSnapshotDtoSource;
  /** @minLength 1 */
  recorderUserId: string;
  note: string;
  capturedAt: string;
}
