/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

export type CreateOrderSettlementDtoStatus = typeof CreateOrderSettlementDtoStatus[keyof typeof CreateOrderSettlementDtoStatus];


export const CreateOrderSettlementDtoStatus = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED',
} as const;
