/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */
import type { CreateOrderDtoStatus } from './createOrderDtoStatus';

export interface CreateOrderDto {
  /** @minLength 1 */
  buyerUserId: string;
  /** @minLength 1 */
  sellerUserId: string;
  /** @minLength 1 */
  baseCurrency: string;
  /** @minLength 1 */
  baseAmount: string;
  /** @minLength 1 */
  quoteCurrency: string;
  /** @minLength 1 */
  quoteAmount: string;
  status: CreateOrderDtoStatus;
  /** @minLength 1 */
  impliedRate: string;
  /** @minLength 1 */
  note: string;
}
