/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

export type CreateCounterpartyDtoType = typeof CreateCounterpartyDtoType[keyof typeof CreateCounterpartyDtoType];


export const CreateCounterpartyDtoType = {
  PERSON: 'PERSON',
  BUSINESS: 'BUSINESS',
  MERCHANT: 'MERCHANT',
  TRADER: 'TRADER',
  COMPANY: 'COMPANY',
  UNKNOWN: 'UNKNOWN',
} as const;
