/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

export interface CreateInventoryLotDto {
  /** @minLength 1 */
  ownerUserId: string;
  /** @minLength 1 */
  assetCurrency: string;
  /** @minLength 1 */
  quantityAcquired: string;
  /** @minLength 1 */
  costCurrency: string;
  /** @minLength 1 */
  totalCostAmount: string;
  /** @minLength 1 */
  sourceOrderId: string;
  /** @minLength 1 */
  sourceTransactionId: string;
  acquiredAt: string;
  note: string;
}
