/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */
import type { CreateTransactionDtoMethod } from './createTransactionDtoMethod';
import type { CreateTransactionDtoType } from './createTransactionDtoType';

export interface CreateTransactionDto {
  /** Business type of the transaction. This determines validation and balance effects. */
  type: CreateTransactionDtoType;
  /** Operational transfer method such as CASH, BANK, WALLET, MANUAL, MIXED, or OTHER. */
  method: CreateTransactionDtoMethod;
  /**
     * Owner context of the transaction. Usually the user whose relationship balances are affected.
     * @minLength 1
     */
  ownerUserId: string;
  /**
     * Internal source user when the transaction originates from a user.
     * @minLength 1
     */
  fromUserId: string;
  /**
     * Internal target user when the transaction goes to a user.
     * @minLength 1
     */
  toUserId: string;
  /**
     * Internal beneficiary when the payment goes elsewhere for that user’s benefit.
     * @minLength 1
     */
  beneficiaryUserId: string;
  /**
     * Optional source institution account reference used for routing and analytics.
     * @minLength 1
     */
  fromAccountId: string;
  /**
     * Optional destination institution account reference used for routing and analytics.
     * @minLength 1
     */
  toAccountId: string;
  /**
     * Optional external source counterparty.
     * @minLength 1
     */
  fromCounterpartyId: string;
  /**
     * Optional external destination counterparty.
     * @minLength 1
     */
  toCounterpartyId: string;
  /**
     * Positive decimal amount as a string.
     * @minLength 1
     */
  amount: string;
  /**
     * Currency code. It will be normalized by the service, for example USD or TRY.
     * @minLength 1
     */
  currency: string;
  /**
     * Optional external reference such as bank reference, receipt number, or tracking code.
     * @minLength 1
     */
  referenceCode: string;
  /**
     * Optional human note that explains the business context of the transaction.
     * @minLength 1
     */
  note: string;
  /** Occurred-at timestamp in ISO-8601 format, for example 2026-04-03T12:00:00.000Z. */
  occurredAt: string;
}
