/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */
import type { CreateSaleExecutionDtoCostBasisMethod } from './createSaleExecutionDtoCostBasisMethod';

export interface CreateSaleExecutionDto {
  /** @minLength 1 */
  ownerUserId: string;
  /** @minLength 1 */
  counterpartyId: string;
  /** @minLength 1 */
  settlementAccountId: string;
  /** @minLength 1 */
  assetCurrency: string;
  /** @minLength 1 */
  quantitySold: string;
  /** @minLength 1 */
  feeCurrency: string;
  /** @minLength 1 */
  feeAmount: string;
  /** @minLength 1 */
  proceedsCurrency: string;
  /** @minLength 1 */
  proceedsAmount: string;
  costBasisMethod: CreateSaleExecutionDtoCostBasisMethod;
  occurredAt: string;
  note: string;
}
