/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

export interface CreateInstitutionAccountDto {
  /** @minLength 1 */
  userId: string;
  /** @minLength 1 */
  institutionId: string;
  /** @minLength 1 */
  currency: string;
  /** @minLength 1 */
  title: string;
  /** @minLength 1 */
  accountIdentifier: string;
  isActive: boolean;
  /** @minLength 1 */
  note: string;
}
