/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

/**
 * Business type of the transaction. This determines validation and balance effects.
 */
export type CreateTransactionDtoType = typeof CreateTransactionDtoType[keyof typeof CreateTransactionDtoType];


export const CreateTransactionDtoType = {
  OPENING_BALANCE: 'OPENING_BALANCE',
  CASH_TO_USER_HOLD: 'CASH_TO_USER_HOLD',
  ACCOUNT_TO_USER_HOLD: 'ACCOUNT_TO_USER_HOLD',
  USER_RETURNS_FUNDS: 'USER_RETURNS_FUNDS',
  INTERNAL_HOLDER_TRANSFER: 'INTERNAL_HOLDER_TRANSFER',
  INTERNAL_ACCOUNT_TRANSFER: 'INTERNAL_ACCOUNT_TRANSFER',
  COUNTERPARTY_IN: 'COUNTERPARTY_IN',
  COUNTERPARTY_OUT: 'COUNTERPARTY_OUT',
  CREATE_DEBT: 'CREATE_DEBT',
  SETTLE_DEBT_DIRECT: 'SETTLE_DEBT_DIRECT',
  SETTLE_DEBT_VIA_COUNTERPARTY: 'SETTLE_DEBT_VIA_COUNTERPARTY',
  EXPENSE: 'EXPENSE',
  ADJUSTMENT: 'ADJUSTMENT',
} as const;
