/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

export type CreateRateSnapshotDtoSource = typeof CreateRateSnapshotDtoSource[keyof typeof CreateRateSnapshotDtoSource];


export const CreateRateSnapshotDtoSource = {
  MANUAL: 'MANUAL',
  MARKET: 'MARKET',
  REFERENCE: 'REFERENCE',
} as const;
