/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

export type CreateOrderSettlementDtoKind = typeof CreateOrderSettlementDtoKind[keyof typeof CreateOrderSettlementDtoKind];


export const CreateOrderSettlementDtoKind = {
  PAYMENT: 'PAYMENT',
  RETURN: 'RETURN',
  FEE: 'FEE',
  ADJUSTMENT: 'ADJUSTMENT',
} as const;
