/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

/**
 * Operational transfer method such as CASH, BANK, WALLET, MANUAL, MIXED, or OTHER.
 */
export type CreateTransactionDtoMethod = typeof CreateTransactionDtoMethod[keyof typeof CreateTransactionDtoMethod];


export const CreateTransactionDtoMethod = {
  CASH: 'CASH',
  BANK: 'BANK',
  WALLET: 'WALLET',
  MANUAL: 'MANUAL',
  MIXED: 'MIXED',
  OTHER: 'OTHER',
} as const;
