/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */
import type { CreateOrderSettlementDtoKind } from './createOrderSettlementDtoKind';
import type { CreateOrderSettlementDtoMethod } from './createOrderSettlementDtoMethod';
import type { CreateOrderSettlementDtoStatus } from './createOrderSettlementDtoStatus';

export interface CreateOrderSettlementDto {
  /** @minLength 1 */
  orderId: string;
  kind: CreateOrderSettlementDtoKind;
  status: CreateOrderSettlementDtoStatus;
  /** @minLength 1 */
  payerUserId: string;
  /** @minLength 1 */
  payeeUserId: string;
  /** @minLength 1 */
  beneficiaryUserId: string;
  /** @minLength 1 */
  toCounterpartyId: string;
  /** @minLength 1 */
  toAccountId: string;
  /** @minLength 1 */
  fromAccountId: string;
  method: CreateOrderSettlementDtoMethod;
  /** @minLength 1 */
  currency: string;
  /** @minLength 1 */
  amount: string;
  /** @minLength 1 */
  note: string;
  dueAt: string;
  paidAt: string;
}
