/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

export interface CreateUserRequestDto {
  /** @minLength 1 */
  name: string;
  /** @minLength 3 */
  username: string;
  /** @minLength 8 */
  password: string;
  isActive: boolean;
}
