/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

export type CreateOrderSettlementDtoMethod = typeof CreateOrderSettlementDtoMethod[keyof typeof CreateOrderSettlementDtoMethod];


export const CreateOrderSettlementDtoMethod = {
  CASH: 'CASH',
  BANK: 'BANK',
  WALLET: 'WALLET',
  MANUAL: 'MANUAL',
  MIXED: 'MIXED',
  OTHER: 'OTHER',
} as const;
