/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */
import type { CreateInstitutionDtoType } from './createInstitutionDtoType';

export interface CreateInstitutionDto {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  country: string;
  type: CreateInstitutionDtoType;
}
