/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

export type CreateSaleExecutionDtoCostBasisMethod = typeof CreateSaleExecutionDtoCostBasisMethod[keyof typeof CreateSaleExecutionDtoCostBasisMethod];


export const CreateSaleExecutionDtoCostBasisMethod = {
  FIFO: 'FIFO',
  WEIGHTED_AVERAGE: 'WEIGHTED_AVERAGE',
} as const;
