/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */
import type { CreateCounterpartyDtoType } from './createCounterpartyDtoType';

export interface CreateCounterpartyDto {
  /** @minLength 1 */
  name: string;
  type: CreateCounterpartyDtoType;
  /** @minLength 1 */
  phone: string;
  /** @minLength 1 */
  note: string;
}
