/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

export type DebtBalancesControllerListV1SortOrder = typeof DebtBalancesControllerListV1SortOrder[keyof typeof DebtBalancesControllerListV1SortOrder];


export const DebtBalancesControllerListV1SortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
