/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */
import type { DebtBalancesControllerListV1SortOrder } from './debtBalancesControllerListV1SortOrder';

export type DebtBalancesControllerListV1Params = {
/**
 * @minimum 1
 * @maximum 9007199254740991
 */
page?: number;
/**
 * @minimum 1
 * @maximum 250
 */
perPage?: number;
/**
 * @minLength 1
 */
select: string;
/**
 * @minLength 1
 */
sortBy: string;
sortOrder?: DebtBalancesControllerListV1SortOrder;
search: string;
/**
 * @minLength 1
 */
debtorUserId: string;
/**
 * @minLength 1
 */
creditorUserId: string;
/**
 * @minLength 1
 */
currency: string;
};
