/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

export type HeldBalancesControllerListV1SortOrder = typeof HeldBalancesControllerListV1SortOrder[keyof typeof HeldBalancesControllerListV1SortOrder];


export const HeldBalancesControllerListV1SortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
