/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */
import type { HeldBalancesControllerListV1SortOrder } from './heldBalancesControllerListV1SortOrder';

export type HeldBalancesControllerListV1Params = {
/**
 * @minimum 1
 * @maximum 9007199254740991
 */
page?: number;
/**
 * @minimum 1
 * @maximum 250
 */
perPage?: number;
/**
 * @minLength 1
 */
select: string;
/**
 * @minLength 1
 */
sortBy: string;
sortOrder?: HeldBalancesControllerListV1SortOrder;
search: string;
/**
 * @minLength 1
 */
ownerUserId: string;
/**
 * @minLength 1
 */
holderUserId: string;
/**
 * @minLength 1
 */
currency: string;
};
