/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

export type InstitutionsControllerListV1SortOrder = typeof InstitutionsControllerListV1SortOrder[keyof typeof InstitutionsControllerListV1SortOrder];


export const InstitutionsControllerListV1SortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
