/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

export type InstitutionAccountsControllerListV1SortOrder = typeof InstitutionAccountsControllerListV1SortOrder[keyof typeof InstitutionAccountsControllerListV1SortOrder];


export const InstitutionAccountsControllerListV1SortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
