/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */
import type { InstitutionAccountsControllerListV1SortOrder } from './institutionAccountsControllerListV1SortOrder';

export type InstitutionAccountsControllerListV1Params = {
/**
 * @minimum 1
 * @maximum 9007199254740991
 */
page?: number;
/**
 * @minimum 1
 * @maximum 250
 */
perPage?: number;
/**
 * @minLength 1
 */
select: string;
/**
 * @minLength 1
 */
sortBy: string;
sortOrder?: InstitutionAccountsControllerListV1SortOrder;
search: string;
/**
 * @minLength 1
 */
userId: string;
/**
 * @minLength 1
 */
institutionId: string;
/**
 * @minLength 1
 */
currency: string;
isActive: boolean;
};
