/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

export type InstitutionsControllerListV1Type = typeof InstitutionsControllerListV1Type[keyof typeof InstitutionsControllerListV1Type];


export const InstitutionsControllerListV1Type = {
  BANK: 'BANK',
  WALLET: 'WALLET',
  EXCHANGE: 'EXCHANGE',
  CASH_OFFICE: 'CASH_OFFICE',
  PAYMENT_APP: 'PAYMENT_APP',
  OTHER: 'OTHER',
} as const;
