/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */
import type { InstitutionsControllerListV1SortOrder } from './institutionsControllerListV1SortOrder';
import type { InstitutionsControllerListV1Type } from './institutionsControllerListV1Type';

export type InstitutionsControllerListV1Params = {
/**
 * @minimum 1
 * @maximum 9007199254740991
 */
page?: number;
/**
 * @minimum 1
 * @maximum 250
 */
perPage?: number;
/**
 * @minLength 1
 */
select: string;
/**
 * @minLength 1
 */
sortBy: string;
sortOrder?: InstitutionsControllerListV1SortOrder;
search: string;
type: InstitutionsControllerListV1Type;
};
