/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

export type InventoryLotsControllerListV1SortOrder = typeof InventoryLotsControllerListV1SortOrder[keyof typeof InventoryLotsControllerListV1SortOrder];


export const InventoryLotsControllerListV1SortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
