/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */
import type { InventoryLotsControllerListV1SortOrder } from './inventoryLotsControllerListV1SortOrder';

export type InventoryLotsControllerListV1Params = {
/**
 * @minimum 1
 * @maximum 9007199254740991
 */
page?: number;
/**
 * @minimum 1
 * @maximum 250
 */
perPage?: number;
/**
 * @minLength 1
 */
select: string;
/**
 * @minLength 1
 */
sortBy: string;
sortOrder?: InventoryLotsControllerListV1SortOrder;
search: string;
/**
 * @minLength 1
 */
ownerUserId: string;
/**
 * @minLength 1
 */
assetCurrency: string;
/**
 * @minLength 1
 */
costCurrency: string;
};
