/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

export interface LoginDto {
  /** @minLength 1 */
  username: string;
  /** @minLength 1 */
  password: string;
}
