/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

export type OrderSettlementsControllerListV1Status = typeof OrderSettlementsControllerListV1Status[keyof typeof OrderSettlementsControllerListV1Status];


export const OrderSettlementsControllerListV1Status = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED',
} as const;
