/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

export type OrderSettlementsControllerListV1SortOrder = typeof OrderSettlementsControllerListV1SortOrder[keyof typeof OrderSettlementsControllerListV1SortOrder];


export const OrderSettlementsControllerListV1SortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
