/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */
import type { OrderSettlementsControllerListV1Kind } from './orderSettlementsControllerListV1Kind';
import type { OrderSettlementsControllerListV1SortOrder } from './orderSettlementsControllerListV1SortOrder';
import type { OrderSettlementsControllerListV1Status } from './orderSettlementsControllerListV1Status';

export type OrderSettlementsControllerListV1Params = {
/**
 * @minimum 1
 * @maximum 9007199254740991
 */
page?: number;
/**
 * @minimum 1
 * @maximum 250
 */
perPage?: number;
/**
 * @minLength 1
 */
select: string;
/**
 * @minLength 1
 */
sortBy: string;
sortOrder?: OrderSettlementsControllerListV1SortOrder;
search: string;
/**
 * @minLength 1
 */
orderId: string;
kind: OrderSettlementsControllerListV1Kind;
status: OrderSettlementsControllerListV1Status;
/**
 * @minLength 1
 */
payerUserId: string;
/**
 * @minLength 1
 */
payeeUserId: string;
/**
 * @minLength 1
 */
beneficiaryUserId: string;
/**
 * @minLength 1
 */
toCounterpartyId: string;
/**
 * @minLength 1
 */
currency: string;
};
