/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

export type OrdersControllerListV1SortOrder = typeof OrdersControllerListV1SortOrder[keyof typeof OrdersControllerListV1SortOrder];


export const OrdersControllerListV1SortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
