/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

export type OrdersControllerListV1Status = typeof OrdersControllerListV1Status[keyof typeof OrdersControllerListV1Status];


export const OrdersControllerListV1Status = {
  OPEN: 'OPEN',
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  PARTIALLY_SETTLED: 'PARTIALLY_SETTLED',
  SETTLED: 'SETTLED',
  CANCELLED: 'CANCELLED',
} as const;
