/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

export type OrderSettlementsControllerListV1Kind = typeof OrderSettlementsControllerListV1Kind[keyof typeof OrderSettlementsControllerListV1Kind];


export const OrderSettlementsControllerListV1Kind = {
  PAYMENT: 'PAYMENT',
  RETURN: 'RETURN',
  FEE: 'FEE',
  ADJUSTMENT: 'ADJUSTMENT',
} as const;
