/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */
import type { OrdersControllerListV1SortOrder } from './ordersControllerListV1SortOrder';
import type { OrdersControllerListV1Status } from './ordersControllerListV1Status';

export type OrdersControllerListV1Params = {
/**
 * @minimum 1
 * @maximum 9007199254740991
 */
page?: number;
/**
 * @minimum 1
 * @maximum 250
 */
perPage?: number;
/**
 * @minLength 1
 */
select: string;
/**
 * @minLength 1
 */
sortBy: string;
sortOrder?: OrdersControllerListV1SortOrder;
search: string;
/**
 * @minLength 1
 */
buyerUserId: string;
/**
 * @minLength 1
 */
sellerUserId: string;
/**
 * @minLength 1
 */
currency: string;
status: OrdersControllerListV1Status;
};
