/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

export type RateSnapshotsControllerListV1SortOrder = typeof RateSnapshotsControllerListV1SortOrder[keyof typeof RateSnapshotsControllerListV1SortOrder];


export const RateSnapshotsControllerListV1SortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
