/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

export type RateSnapshotsControllerListV1Source = typeof RateSnapshotsControllerListV1Source[keyof typeof RateSnapshotsControllerListV1Source];


export const RateSnapshotsControllerListV1Source = {
  MANUAL: 'MANUAL',
  MARKET: 'MARKET',
  REFERENCE: 'REFERENCE',
} as const;
