/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */
import type { RateSnapshotsControllerListV1SortOrder } from './rateSnapshotsControllerListV1SortOrder';
import type { RateSnapshotsControllerListV1Source } from './rateSnapshotsControllerListV1Source';

export type RateSnapshotsControllerListV1Params = {
/**
 * @minimum 1
 * @maximum 9007199254740991
 */
page?: number;
/**
 * @minimum 1
 * @maximum 250
 */
perPage?: number;
/**
 * @minLength 1
 */
select: string;
/**
 * @minLength 1
 */
sortBy: string;
sortOrder?: RateSnapshotsControllerListV1SortOrder;
search: string;
/**
 * @minLength 1
 */
baseCurrency: string;
/**
 * @minLength 1
 */
quoteCurrency: string;
source: RateSnapshotsControllerListV1Source;
};
