/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

export type SaleExecutionsControllerListV1SortOrder = typeof SaleExecutionsControllerListV1SortOrder[keyof typeof SaleExecutionsControllerListV1SortOrder];


export const SaleExecutionsControllerListV1SortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
