/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

export type SaleExecutionsControllerListV1CostBasisMethod = typeof SaleExecutionsControllerListV1CostBasisMethod[keyof typeof SaleExecutionsControllerListV1CostBasisMethod];


export const SaleExecutionsControllerListV1CostBasisMethod = {
  FIFO: 'FIFO',
  WEIGHTED_AVERAGE: 'WEIGHTED_AVERAGE',
} as const;
