/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

export type TransactionsControllerListV1SortOrder = typeof TransactionsControllerListV1SortOrder[keyof typeof TransactionsControllerListV1SortOrder];


export const TransactionsControllerListV1SortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
