/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

export type TransactionsControllerListV1Method = typeof TransactionsControllerListV1Method[keyof typeof TransactionsControllerListV1Method];


export const TransactionsControllerListV1Method = {
  CASH: 'CASH',
  BANK: 'BANK',
  WALLET: 'WALLET',
  MANUAL: 'MANUAL',
  MIXED: 'MIXED',
  OTHER: 'OTHER',
} as const;
