/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */
import type { TransactionsControllerListV1Method } from './transactionsControllerListV1Method';
import type { TransactionsControllerListV1SortOrder } from './transactionsControllerListV1SortOrder';
import type { TransactionsControllerListV1Type } from './transactionsControllerListV1Type';

export type TransactionsControllerListV1Params = {
/**
 * @minimum 1
 * @maximum 9007199254740991
 */
page?: number;
/**
 * @minimum 1
 * @maximum 250
 */
perPage?: number;
/**
 * @minLength 1
 */
select: string;
/**
 * @minLength 1
 */
sortBy: string;
sortOrder?: TransactionsControllerListV1SortOrder;
search: string;
/**
 * Filter by transaction owner user.
 * @minLength 1
 */
ownerUserId: string;
/**
 * Filter by authenticated user who created or initiated the transaction.
 * @minLength 1
 */
initiatorUserId: string;
/**
 * Filter by internal source user.
 * @minLength 1
 */
fromUserId: string;
/**
 * Filter by internal destination user.
 * @minLength 1
 */
toUserId: string;
/**
 * Filter by internal beneficiary user.
 * @minLength 1
 */
beneficiaryUserId: string;
/**
 * Filter by source institution account.
 * @minLength 1
 */
fromAccountId: string;
/**
 * Filter by destination institution account.
 * @minLength 1
 */
toAccountId: string;
/**
 * Filter by external source counterparty.
 * @minLength 1
 */
fromCounterpartyId: string;
/**
 * Filter by external destination counterparty.
 * @minLength 1
 */
toCounterpartyId: string;
/**
 * Filter by currency code.
 * @minLength 1
 */
currency: string;
/**
 * Filter by transaction type.
 */
type: TransactionsControllerListV1Type;
/**
 * Filter by transfer method.
 */
method: TransactionsControllerListV1Method;
/**
 * Filter transactions that occurred at or after this ISO-8601 timestamp.
 */
occurredFrom: string;
/**
 * Filter transactions that occurred at or before this ISO-8601 timestamp.
 */
occurredTo: string;
};
