/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */
import type { UpdateInstitutionDtoType } from './updateInstitutionDtoType';

export interface UpdateInstitutionDto {
  /** @minLength 1 */
  name?: string;
  country?: string;
  type?: UpdateInstitutionDtoType;
}
