/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */
import type { UpdateCounterpartyDtoType } from './updateCounterpartyDtoType';

export interface UpdateCounterpartyDto {
  /** @minLength 1 */
  name?: string;
  type?: UpdateCounterpartyDtoType;
  phone?: string;
  note?: string;
}
