/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

export interface UpdateInstitutionAccountDto {
  /** @minLength 1 */
  title?: string;
  /** @minLength 1 */
  currency?: string;
  accountIdentifier?: string;
  isActive?: boolean;
  note?: string;
}
