/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

export interface UpdateUserDto {
  /** @minLength 1 */
  name?: string;
}
