/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */
import type { UpdateOrderDtoStatus } from './updateOrderDtoStatus';

export interface UpdateOrderDto {
  status?: UpdateOrderDtoStatus;
  note?: string;
}
