/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * xeBook API backend
 * xeBook API backend
 * OpenAPI spec version: 1.0
 */

export type UsersControllerListV1SortOrder = typeof UsersControllerListV1SortOrder[keyof typeof UsersControllerListV1SortOrder];


export const UsersControllerListV1SortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
